profiles:
  Logi C270:
    black:
      H_lower: 0
      H_upper: 179
      S_lower: 0
      S_upper: 101
      V_lower: 0
      V_upper: 105
    red:
      H_lower: 0
      H_upper: 11
      S_lower: 86
      S_upper: 255
      V_lower: 0
      V_upper: 255
    white:
      H_lower: 0
      H_upper: 179
      S_lower: 0
      S_upper: 176
      V_lower: 248
      V_upper: 255
    yellow:
      H_lower: 11
      H_upper: 47
      S_lower: 154
      S_upper: 255
      V_lower: 0
      V_upper: 255
  default:
    blue:
      H_lower: 50
      H_upper: 179
      S_lower: 143
      S_upper: 255
      V_lower: 225
      V_upper: 255
    red:
      H_lower: 0
      H_upper: 24
      S_lower: 161
      S_upper: 255
      V_lower: 116
      V_upper: 255
    yellow:
      H_lower: 18
      H_upper: 26
      S_lower: 143
      S_upper: 255
      V_lower: 150
      V_upper: 206
