profiles:
  default:
    camera_port_1: 0
    camera_port_2: -1
    calibrate_cameras: False
    calibration_folders: []
    time_between_stitch: 1.0
    camera_width: 1280
    camera_height: 720
    output_width: 1920
    output_height: 1080
    detector:
      profile: "default"
      radius: 50
      table_area: 20000
    tracking:
      buffer_size: 64
      center_point_color:
        - 0
        - 0
        - 255
      center_point_radius: 5
      circle_outline_color:
        - 0
        - 255
        - 255
      circle_thickness: 2
      font_color:
        - 255
        - 255
        - 255
      font_scale: 0.5
      font_thickness: 2
      max_distance: 50
      min_area: 200
      radius_line_color:
        - 255
        - 0
        - 0
      radius_line_thickness: 2
      tracking_line_color:
        - 0
        - 0
        - 255

  logi_c270:
    camera_port_1: 1
    camera_port_2: -1
    calibrate_cameras: True
    calibration_folders: ["/logi_c270_cam1", "/logi_c270_cam2"]
    time_between_stitch: 1.0
    camera_width: 1280
    camera_height: 720
    output_width: 1920
    output_height: 1080
    detector:
      profile: "Logi C270"
      radius: 50
      table_area: 3000
    tracking:
      buffer_size: 64
      center_point_color:
        - 0
        - 0
        - 255
      center_point_radius: 5
      circle_outline_color:
        - 0
        - 255
        - 255
      circle_thickness: 2
      font_color:
        - 255
        - 255
        - 255
      font_scale: 0.5
      font_thickness: 2
      max_distance: 50
      min_area: 8000
      radius_line_color:
        - 255
        - 0
        - 0
      radius_line_thickness: 2
      tracking_line_color:
        - 0
        - 0
        - 255
