profiles:
  default:
    buffer_size: 64
    calibrate_cameras: false
    calibration_folders: []
    camera_port_1: 0
    camera_port_2: -1
    center_point_color:
      - 0
      - 0
      - 255
    center_point_radius: 5
    circle_outline_color:
      - 0
      - 255
      - 255
    circle_thickness: 2
    font_color:
      - 255
      - 255
      - 255
    font_scale: 0.5
    font_thickness: 2
    max_distance: 50
    min_area: 1000
    profile: default
    radius: 50
    radius_line_color:
      - 255
      - 0
      - 0
    radius_line_thickness: 2
    table_area: 1000
    time_between_stitch: 1.0
    tracking_line_color:
      - 0
      - 0
      - 255
  logi_c270:
    buffer_size: 64
    calibrate_cameras: true
    calibration_folders: ["/logi_c270_cam1", "/logi_c270_cam2"]
    camera_port_1: 0
    camera_port_2: -1
    center_point_color:
      - 0
      - 0
      - 255
    center_point_radius: 5
    circle_outline_color:
      - 0
      - 255
      - 255
    circle_thickness: 2
    font_color:
      - 255
      - 255
      - 255
    font_scale: 0.5
    font_thickness: 2
    max_distance: 50
    min_area: 1000
    profile: "Logi C270"
    radius: 50
    radius_line_color:
      - 255
      - 0
      - 0
    radius_line_thickness: 2
    table_area: 1000
    time_between_stitch: 1.0
    tracking_line_color:
      - 0
      - 0
      - 255
