calibrate_camera: true
calibration_folder: "./config/calibration/wide_angle_cam"
camera_port: 2
font_color:
  - 255
  - 255
  - 255
font_scale: 0.5
font_thickness: 2
use_networking: False
detection_model_path: "model/detection_model.pt"
conf_threshold: 0.5
clean_images_path: "model/clean_images/"
model_training_path: "model/training_images/calibration/edge_cases/"
anomaly_threshold: 0.017
anomaly_buffer_size: 6
autoencoder_model_path: "model/autoencoder_model.keras"
network_update_interval: 0.1
position_threshold: 3
poolpal_url: "http://poolpal.joshn.uk"
poolpal_subdomain: "pool-pal"
output_width: 1200
output_height: 600
hole_threshold: 30
calibration_mode: -1
