profiles:
  default:
    calibrate_camera: true
    calibration_folder: ["./config/calibration/wide_angle_cam"]
    camera_port: 2
    font_color:
      - 255
      - 255
      - 255
    font_scale: 0.5
    font_thickness: 2
    use_networking: False
    detection_model_path: "model/ball_detection_model.pt"
    conf_threshold: 0.5
    clean_images_path: "model/clean_images/"
    model_training_path: "model/training_images/calibration/"
    anomaly_threshold: 0.01
    autoencoder_model_path: "model/autoencoder_model.keras"
    network_update_interval: 0.5
    position_threshold: 3
    poolpal_url: "https://pool-pal.serveo.net"
    poolpal_subdomain: "pool-pal"
