profiles:
  default:
    calibrate_cameras: false
    calibration_folders: []
    camera_port_1: 0
    camera_port_2: -1
    font_color:
      - 255
      - 255
      - 255
    font_scale: 0.5
    font_thickness: 2
    use_networking: True
    detection_model_path: "model/ball_detection_model.pt"
    conf_threshold: 0.5
    clean_images_path: "model/clean_images"
    model_training_path: "model/training_images"
    anomaly_threshold: 0.01
    autoencoder_model_path: "model/autoencoder_model.keras"
    network_update_interval: 2
    position_threshold: 3
    poolpal_url: "http://localhost:5000"
    poolpal_subdomain: "pool-pal"
